[config]
skip_core_tasks = true

[tasks.app]
workspace = false
command = "cargo"
args = ["run", "--release", "--bin", "app"]
env_files = [".env"]

[tasks.server]
workspace = false
command = "cargo"
args = ["run", "--bin", "server"]
watch = { watch = ["server", "essentials"] }
env_files = [".env"]

[tasks.gui]
workspace = false
command = "cargo"
args = ["run", "--bin", "gui"]
watch = { watch = ["gui", "essentials"] }
