@host=http://localhost:3000

{{
  const token = "test"
  exports.defaultHeaders = {
    'Content-Type': 'application/json',
  };
}}
###

# @name search records
GET /password?search=
###
# @name get password
POST /password/clcniqsyx000015h49s5x39bg
...defaultHeaders
{
    "key": "qweqweqwe"
}
###
# @name create password
POST /password
...defaultHeaders
{
    "title": "I dont like to share this with anyone",
    "key": "qweqweqwe",
    "login": "pussy@gmail.com",
    "password": "what is dis",
    "resources": [
        {
            "URL": "pornhub.com"
        }
    ]
}
###
# @name update password2
PUT /password/clcniqsyx000015h49s5x39bg
...defaultHeaders
{
    "title": "Changed",
    "key": "qweqweqwe",
    "login": "wow@gmail.com",
    "password": "yyy",
    "resources": [
        {
            "URL": "kek.com"
        }
    ]
}
###
# @name delete password
DELETE /password/clcj1yhu7000015jwdwsj9nnt
###